import React from "react";
import { Zap } from "lucide-react";
import { fmtDateLong } from "../utils/rowsConfig.js";

export default function ReportHeader({ title, date, generatedTime, generatedBy }) {
  return (
    <div className="border-b border-slate-700 pb-4 mb-5">
      <div className="flex items-center gap-3 mb-3">
        <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center shrink-0">
          <Zap size={22} className="text-slate-950" />
        </div>
        <div>
          <div className="font-extrabold text-white text-base leading-tight">APL Apollo Building Products Ltd.</div>
          <div className="text-xs text-slate-400">Electrical Department</div>
        </div>
      </div>
      <h1 className="text-lg font-extrabold text-cyan-300 tracking-wide text-center py-2">{title}</h1>
      <div className="flex flex-wrap justify-between gap-2 text-[11.5px] text-slate-400 mt-2">
        <span>Report Date: <b className="text-slate-200">{fmtDateLong(date)}</b></span>
        <span>Generated Time: <b className="text-slate-200">{generatedTime ? new Date(generatedTime).toLocaleString() : "—"}</b></span>
        <span>Generated By: <b className="text-slate-200">{generatedBy || "—"}</b></span>
      </div>
    </div>
  );
}
