import React from "react";

// Har word ke liye alag-alag bright aur bold colors ka palette
const TITLE_WORD_COLORS = [
  "text-blue-700",
  "text-rose-700",
  "text-amber-600",
  "text-emerald-700",
  "text-purple-700",
  "text-cyan-700",
  "text-indigo-700",
];

export default function ReportHeader({ title, date, generatedTime, generatedBy }) {
  // Title string ko break karke har word ko alag color aur bold style dene ka logic
  const renderColoredTitle = () => {
    if (typeof title !== "string") return title;

    const words = title.trim().split(/\s+/);
    return words.map((word, index) => {
      const colorClass = TITLE_WORD_COLORS[index % TITLE_WORD_COLORS.length];
      return (
        <span key={index} className={`${colorClass} font-black inline-block mr-2`}>
          {word}
        </span>
      );
    });
  };

  return (
    <div className="border-b-2 border-slate-300 pb-4 mb-6">
      {/* Title Header - Each Word Different Color & Ultra-Bold */}
      <div className="mb-4">
        <h1 className="text-2xl md:text-3xl tracking-wide uppercase flex flex-wrap items-center">
          {renderColoredTitle()}
        </h1>
      </div>

      {/* Report Metadata Row - Different Colors & Bold Text */}
      <div className="flex flex-wrap items-center justify-between text-xs gap-3 font-black bg-slate-100/80 p-3.5 rounded-2xl border-2 border-slate-300">
        
        {/* Report Date (Cyan / Blue Theme) */}
        <div className="flex items-center gap-1.5 bg-white px-3 py-1.5 rounded-xl border border-slate-300 shadow-xs">
          <span className="text-slate-700 uppercase font-black">Report Date:</span>
          <span className="text-cyan-800 text-xs font-black">{date || "—"}</span>
        </div>

        {/* Generated Time (Emerald Green Theme) */}
        <div className="flex items-center gap-1.5 bg-white px-3 py-1.5 rounded-xl border border-slate-300 shadow-xs">
          <span className="text-slate-700 uppercase font-black">Generated Time:</span>
          <span className="text-emerald-700 text-xs font-black">
            {generatedTime ? new Date(generatedTime).toLocaleString() : "—"}
          </span>
        </div>

        {/* Generated By (Purple Theme) */}
        <div className="flex items-center gap-1.5 bg-white px-3 py-1.5 rounded-xl border border-slate-300 shadow-xs">
          <span className="text-slate-700 uppercase font-black">Generated By:</span>
          <span className="text-purple-800 text-xs font-black">{generatedBy || "Admin"}</span>
        </div>

      </div>
    </div>
  );
}